#!/bin/bash

set -e

yarn build
git checkout gh-pages
find . -not -path './.git*' -not -path './dist' -not -path './dist/*' -not -path './node_modules' -not -path './node_modules/*' -delete
mv dist/* .
rm -rf dist
git add .
git commit --amend --no-edit
git push --force
git checkout master
